title: Colin Zhou blog
description: I write and muse about various topics as a software engineer in the Bay Area.
baseurl: "/blog"
url: "https://czhou578.github.io"
theme: minima

github_username: czhou578
twitter_username: ColinZhouUSA
