title: Colin Zhou blog
description: I write and muse about various topics.
baseurl: "/blog"
url: "https://czhou578.github.io"
theme: minima

author:
  name: Colin Zhou

github_username: czhou578
twitter_username: ColinZhouUSA
